require("theprimeagen")
-- RESOURCES
-- https://github.com/wbthomason/packer.nvim
-- https://github.com/nvim-telescope/telescope.nvim
-- https://github.com/rose-pine/neovim
-- https://github.com/nvim-treesitter/nvim-treesitter
-- https://github.com/nvim-treesitter/playground
-- https://github.com/ThePrimeagen/harpoon
-- https://github.com/mbbill/undotree
-- https://github.com/tpope/vim-fugitive
-- https://github.com/VonHeikemen/lsp-zero.nvim
-- https://github.com/folke/trouble.nvim
--
-- RESSOURCES "USELESS BUT FUN"
-- https://github.com/Eandrju/cellular-automaton.nvim
